-- MySQL Script generated by MySQL Workbench
-- 07/12/17 16:44:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `ProdCod` INT NOT NULL,
  `ProNom` VARCHAR(45) NOT NULL,
  `Qtde` INT NOT NULL,
  `ProPreco` DECIMAL(2) NOT NULL,
  `PrecIPI` DECIMAL(2) NOT NULL,
  `PrecICMS` DECIMAL(2) NOT NULL,
  `Ind` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ProdCod`),
  UNIQUE INDEX `ProdCodi_UNIQUE` (`ProdCod` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `VendCod` INT NOT NULL,
  `VendNom` VARCHAR(45) NOT NULL,
  `VendRG` INT NOT NULL,
  `VendCPF` INT NOT NULL,
  PRIMARY KEY (`VendCod`),
  UNIQUE INDEX `VendCod_UNIQUE` (`VendCod` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `CliCodi` INT NOT NULL,
  `CliNome` VARCHAR(45) NOT NULL,
  `Perfil` VARCHAR(45) NOT NULL,
  `CliEmail` VARCHAR(45) NOT NULL,
  `CliFone` INT NOT NULL,
  `CliEnde` VARCHAR(45) NOT NULL,
  `VendCod` INT NOT NULL,
  PRIMARY KEY (`CliCodi`),
  UNIQUE INDEX `CliCodi_UNIQUE` (`CliCodi` ASC),
  INDEX `VendCod_idx` (`VendCod` ASC),
  CONSTRAINT `VendCod`
    FOREIGN KEY (`VendCod`)
    REFERENCES `mydb`.`vendedor` (`VendCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `ItemCod` INT NOT NULL,
  `ItemQtd` INT NOT NULL,
  `ProCodi` INT NOT NULL,
  PRIMARY KEY (`ItemCod`),
  UNIQUE INDEX `ItemCod_UNIQUE` (`ItemCod` ASC),
  INDEX `ProCodi_idx` (`ProCodi` ASC),
  CONSTRAINT `ProCodi`
    FOREIGN KEY (`ProCodi`)
    REFERENCES `mydb`.`produto` (`ProdCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nota` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `NotaCod` INT NOT NULL,
  `NotaNum` INT NOT NULL,
  `DataVenda` DATETIME NOT NULL,
  `ItemCod` INT NOT NULL,
  `CliCodi` INT NOT NULL,
  PRIMARY KEY (`NotaCod`),
  UNIQUE INDEX `NotaCod_UNIQUE` (`NotaCod` ASC),
  INDEX `ItemCod_idx` (`ItemCod` ASC),
  INDEX `CliCod_idx` (`CliCodi` ASC),
  CONSTRAINT `ItemCod`
    FOREIGN KEY (`ItemCod`)
    REFERENCES `mydb`.`item` (`ItemCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CliCod`
    FOREIGN KEY (`CliCodi`)
    REFERENCES `mydb`.`cliente` (`CliCodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `CidaCod` INT NOT NULL,
  `CidaNom` VARCHAR(45) NOT NULL,
  `CliCodi` INT NOT NULL,
  PRIMARY KEY (`CidaCod`),
  UNIQUE INDEX `CidaCod_UNIQUE` (`CidaCod` ASC),
  INDEX `CliCodi_idx` (`CliCodi` ASC),
  CONSTRAINT `CliCodi`
    FOREIGN KEY (`CliCodi`)
    REFERENCES `mydb`.`cliente` (`CliCodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `EstaCod` INT NOT NULL,
  `EstaNom` VARCHAR(45) NOT NULL,
  `PercICMS` INT NOT NULL,
  `CidaCod` INT NOT NULL,
  PRIMARY KEY (`EstaCod`),
  UNIQUE INDEX `EstaCod_UNIQUE` (`EstaCod` ASC),
  INDEX `CidaCod_idx` (`CidaCod` ASC),
  CONSTRAINT `CidaCod`
    FOREIGN KEY (`CidaCod`)
    REFERENCES `mydb`.`cidade` (`CidaCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`natureza_operacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`natureza_operacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`natureza_operacao` (
  `NatuCod` INT NOT NULL,
  `NatuDesc` VARCHAR(45) NOT NULL,
  `NotaCod` INT NOT NULL,
  PRIMARY KEY (`NatuCod`),
  UNIQUE INDEX `NatuCod_UNIQUE` (`NatuCod` ASC),
  INDEX `NotaCod_idx` (`NotaCod` ASC),
  CONSTRAINT `NotaCod`
    FOREIGN KEY (`NotaCod`)
    REFERENCES `mydb`.`nota` (`NotaCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `GrupCod` INT NOT NULL,
  `GrupNom` VARCHAR(45) NOT NULL,
  `ProdCod` INT NOT NULL,
  PRIMARY KEY (`GrupCod`),
  UNIQUE INDEX `GrupCod_UNIQUE` (`GrupCod` ASC),
  INDEX `ProdCod_idx` (`ProdCod` ASC),
  CONSTRAINT `ProdCod`
    FOREIGN KEY (`ProdCod`)
    REFERENCES `mydb`.`produto` (`ProdCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`familia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`familia` (
  `FamiCod` INT NOT NULL,
  `FamiNom` VARCHAR(45) NOT NULL,
  `GrupCod` INT NOT NULL,
  PRIMARY KEY (`FamiCod`),
  UNIQUE INDEX `FamiCod_UNIQUE` (`FamiCod` ASC),
  INDEX `GrupCod_idx` (`GrupCod` ASC),
  CONSTRAINT `GrupCod`
    FOREIGN KEY (`GrupCod`)
    REFERENCES `mydb`.`grupo` (`GrupCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone_cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone_cliente` (
  `TeleCCod` INT NOT NULL,
  `TeleCNum` INT NOT NULL,
  `CliCodi` INT NOT NULL,
  PRIMARY KEY (`TeleCCod`),
  UNIQUE INDEX `TeleCod_UNIQUE` (`TeleCCod` ASC),
  INDEX `CliCodi_idx` (`CliCodi` ASC),
  CONSTRAINT `CliCodi`
    FOREIGN KEY (`CliCodi`)
    REFERENCES `mydb`.`cliente` (`CliCodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone_vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone_vendedor` (
  `TeleVCod` INT NOT NULL,
  `TeleVNum` INT NOT NULL,
  `VendCod` INT NOT NULL,
  PRIMARY KEY (`TeleVCod`),
  UNIQUE INDEX `TeleVCod_UNIQUE` (`TeleVCod` ASC),
  INDEX `VendCod_idx` (`VendCod` ASC),
  CONSTRAINT `VendCod`
    FOREIGN KEY (`VendCod`)
    REFERENCES `mydb`.`vendedor` (`VendCod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
